update and fix bug
Desplay/NestJS_MongoDB_GraphQL_Basic pull request #5
Opened 2023-08-08 14:08 UTC by Desplay

2023-08-08 14:30 UTC, phanhuutoan requested changes
Kiến trúc tương đối ổn, cần refactor thêm

2023-08-08 14:30 UTC, phanhuutoan commented on src/auth/auth.resolver.ts
> +  @Mutation(() => Authorization)
AuthPayload !== Authorization

2023-08-08 14:30 UTC, phanhuutoan commented on src/auth/auth.resolver.ts
> +  @Mutation(() => Authorization)
Auth...Type

2023-08-08 14:30 UTC, phanhuutoan commented on src/auth/auth.validate.ts
> +import { ForbiddenException, Injectable } from '@nestjs/common';
authValidator.service.ts

2023-08-08 14:30 UTC, phanhuutoan commented on src/auth/auth.validate.ts
> +    if (user.OTPCode.dateExpired < new Date().getTime())
`{ OTPCode } = user`

2023-08-08 14:30 UTC, phanhuutoan commented on src/auth/auth.validate.ts
> +    if (user.OTPCode.dateExpired < new Date().getTime())
throw new Exception('OTP code is invalid')

2023-08-08 14:30 UTC, phanhuutoan commented on src/common/jwt/jwt.service.ts
> +  private validatePayload(payload: Payload): boolean {
Best practice private xuống dưới

2023-08-08 14:30 UTC, phanhuutoan commented on src/common/jwt/jwt.service.ts
> +      payload['exp'] === undefined;
`validPayload = payload[a] && payload[b] && payload[c]`

2023-08-10 08:46 UTC, Desplay commented
> Kiến trúc tương đối ổn, cần refactor thêm

all this fix done !

2023-08-10 08:48 UTC, Desplay commented
> 

this is change: https://github.com/Desplay/NestJS_MongoDB_GraphQL_Basic/pull/5/commits/ffb24c9f9034c66153bcd568f44946fc658c59bc

2023-08-31 11:16 UTC, Desplay commented
All in done, create Comments services & Like Services, allready merge in main brain

2023-08-31 11:16 UTC, merged